version: "3.7"

volumes:
  db:

services:
  &mysql test-mysql:
    container_name: *mysql
    hostname: *mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: &MYSQL_ROOT_PASS examplepass5
    volumes:
      - db:/var/lib/mysql
    networks:
      - web
      
  &php-fpm test-php-fpm:
    container_name: *php-fpm
    hostname: *php-fpm
    command: php-fpm
    environment:
      FPM_PORT: &PHP74_PORT 9000
      FPM_USER: "${CURRENT_USER_ID}"
      FPM_GROUP: "${CURRENT_USER_ID}"
      CURRENT_USER: "${CURRENT_USER}"
      SCHEDULE_PERIOD: 60
      restart: always
    volumes:
      - ./www:/var/www/html:rw
    build: 
      ./docker/php
    networks:
      - web

  &httpd  test-httpd:
    container_name: *httpd
    hostname: *httpd
    environment:
      PHP74_HOST: *php-fpm
      PHP74_PORT: *PHP74_PORT
    depends_on: 
      - *mysql
    ports:
      - ${APACHE_CONTAINER_PORT}:80
    restart: always
    volumes:
      - ./www:/var/www/html:rw
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    build: 
      ./docker/apache
    networks:
      - web
  

  &pma test-phpmyadmin:
    container_name: *pma
    hostname: *pma
    restart: always
    depends_on:
      - *mysql
    ports:
      - ${PHPMYADMIN_CONTAINER_PORT}:80
    image: phpmyadmin
    environment:
      PMA_HOST: *mysql
      MYSQL_ROOT_PASSWORD: *MYSQL_ROOT_PASS
      UPLOAD_LIMIT: "1G"
    networks:
      - web

  &node test-node:
    container_name: *node
    hostname: *node
    restart: on-failure
    user: "1000:1000"
    build:
       ./docker/node
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html:rw
    networks:
      - web
networks:
  web: 